name: Push to publish
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Push to publish
        uses: fabian4/actions-push-anydir-to-anydir@main
        env: 
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-folder: BigData/;Gateway/
          dest-repo: 'fabian4/draftbook'
          dest-folder: 'docs'
          commit-message: 'sync commit'
          excludes: .vuepress/;README.md
