name: Push to publish
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Push to publish
        uses: NoahDragon/action-push-repo-as-subdirectory-in-another-repo@main
        env: 
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          dest-repo: 'fabian4/draftbook'
          dest-folder: 'docs'
          commit-message: 'sync commit'
          excludes: .vuepress/;README.md
